### PR TITLE
UHF-3596: Finalize styling for the remote video paragraph

### PR DESCRIPTION
**Pull request by teroelonen**
#  Remote-video paragraph changes [UHF-3596](https://helsinkisolutionoffice.atlassian.net/browse/UHF-3596)

## How to test
* Testing instructions and descriptions written in the helfi_platform_config PR.

## Other PRs
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/266
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/100
* https://github.com/City-of-Helsinki/drupal-helfi-strategia/pull/224
* https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/318
* https://github.com/City-of-Helsinki/drupal-helfi-asuminen/pull/53
* https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/321
* https://github.com/City-of-Helsinki/drupal-helfi-tyo-yrittaminen/pull/58

### CODE REVIEW

**Review by khalima — CHANGES_REQUESTED** [review]
This happens when viewing the video paragraph on mobile in basic page lower content. 
image
The margins/paddings are nowhere to be seen. On upper content area this doesn't happen nor in any of the other content and entity types.

**Review by khalima — CHANGES_REQUESTED** [review]
Found another bug. When trying to view the videos without cookies accepted, the following happens.
image

**Comment by teroelonen** [comment]
Fixed the cookie-issue too :)

**Review by khalima — APPROVED** [review]
Works as described. 🚀

**Pull request merged**
