### PR TITLE
UHF-3424: Opening hours in unit teaser

### PR DESCRIPTION
**Pull request by Arkkimaagi**
# [UHF-3424](https://helsinkisolutionoffice.atlassian.net/browse/UHF-3424)

## What was done

* Opening hours were re-introduced to the unit card
* Card layout was rewritten as the designs changed
* Card was renamed to content-liftup to follow the paragraph naming
* Card template was separated from tpr-unit template to its own file
* Supports swedish was removed from this card as requested by designer (confirmed with PO)
* Translations were added
* Extra spaces were removed from address template to reduce css complexity
* Layout logic was discussed and designed together with design, see comments below for approved screenshots

## How to test

* Get this branch
* Add content-liftup to landing page, basic page, in upper and lower regions, should work the same in all instances
  * Add unit with long opening hours
  * Add unit with short opening hours
  * Add unit without opening hours
  * Add unit with image
  * Add unit without image (sitewide fallback should be in use with custom color and icon)
* Check with 3 different breakpoint areas
  * 320px - 767px (mobile - breakpoint-m)
  * 768px - 991px (breakpoint-m - breakpoint-l)
  * 992px - (breakpoint-l - wide)

### CODE REVIEW

**Comment by Arkkimaagi** [comment]
320px, mobile size example, notice that in this screenshot the arrow-right is incorrectly in another row, in code this has been fixed.

image

**Comment by Arkkimaagi** [comment]
767px wide, just before first breakpoint-m switch, style should be identical to 320px, but just wider
image

**Comment by Arkkimaagi** [comment]
768px wide, images are now in left column, their width follows the logic from next breakpoint-l
image

**Comment by Arkkimaagi** [comment]
991px wide, same as above, more stretched, just before breakpoint-l

image

**Comment by Arkkimaagi** [comment]
992px wide, cards in that have sidebar next to them have their text-area kept identical to cards without sidebar. Basically it's close to a little less than 30% width of card.

image

**Comment by Arkkimaagi** [comment]
2560px, same as above, but the max width of cards visible
image

**Review by khalima — APPROVED** [review]
Works exactly as described! 🚀

**Pull request merged**
